"""Bundled punishment decks (spec §5.3). Server-authoritative — never sent
to the client; only the dealt card text crosses the wire.

Tone ladder:
- mild  — silly, all-ages party dares.
- spicy — bolder adult-party dares (flirty/embarrassing, tasteful;
          no explicit NSFW, nothing unsafe or non-consensual).
- chaos — absurd wildcard dares.

Writing rules (so cards read clearly on a phone mid-party):
- Each card is ONE clear action the PUNISHED player performs themselves —
  never an ambiguous "let the group do X" where it's unclear what to do.
- Natural, idiomatic language per locale (spec §6); en/uk are written
  natively and do NOT align by index.
The integrity test (exactly CARDS_PER_DECK unique non-empty per deck×lang)
is the gate. Dealing is no-repeat-until-exhausted (see services/punishment.py).
"""

from __future__ import annotations

import structlog

log = structlog.get_logger("hoba_api.modes.punishment_decks")

DECK_IDS = ("mild", "spicy", "chaos")
DECK_LANGS = ("en", "uk")
CARDS_PER_DECK = 40

DECKS: dict[str, dict[str, list[str]]] = {
    "mild": {
        "en": [
            "Speak in a robot voice until your next turn.",
            "Do an impression of someone here — let others guess who.",
            "Sing the chorus of any song right now.",
            "Talk only in rhymes until your next turn.",
            "Do 10 jumping jacks.",
            "Tell a funny story from your childhood.",
            "Walk across the room like a runway model.",
            "Speak in any accent until your next turn.",
            "Show the last photo in your camera roll.",
            "Do your best impression of a crying baby.",
            "Compliment everyone in the room, one by one.",
            "Hold a plank until your next turn.",
            "Do your best evil-villain laugh.",
            "Act out your favourite animal — sound and moves.",
            "Make up and sing a 10-second jingle about this group.",
            "Wear your shirt backwards until your next turn.",
            "Do a dramatic movie death scene.",
            "Say the alphabet backwards from M.",
            "Give a 20-second solemn speech about your socks.",
            "Dance like nobody's watching for 15 seconds.",
            "Be a news anchor reading the weather forecast.",
            "Balance a spoon on your nose for 10 seconds.",
            "Tell a joke. If nobody laughs, tell another one.",
            "Speak only in a whisper until your next turn.",
            "Do 5 squats, counting out loud.",
            "Become a superhero: invent your name and your power.",
            "Act out waking up on a Monday morning.",
            "Talk to your hand as if it's your friend.",
            "Describe the taste of water like a sommelier.",
            "Show your single best dance move.",
            "Talk about yourself in the third person until your next turn.",
            "Freeze like a statue until someone says your name.",
            "Sing what you did today, opera-style.",
            "The floor is lava for the next 30 seconds.",
            "Show how you dance at a wedding.",
            "Say a tongue-twister three times in a row, no mistakes.",
            "Quote your favourite movie character in one line.",
            "Make a finger moustache and keep it until your next turn.",
            "Greet everyone as if you haven't seen them in 10 years.",
            "Host a cooking show and 'make' an imaginary dish.",
        ],
        "uk": [
            "Говори голосом робота до свого наступного ходу.",
            "Зобрази когось із присутніх — нехай інші вгадають, хто це.",
            "Заспівай приспів будь-якої пісні просто зараз.",
            "Говори лише римами до свого наступного ходу.",
            "Зроби 10 стрибків «джампінг-джек».",
            "Розкажи смішну історію зі свого дитинства.",
            "Пройдись по кімнаті, як модель на подіумі.",
            "Говори з будь-яким акцентом до свого наступного ходу.",
            "Покажи останнє фото у своїй галереї.",
            "Зобрази, як плаче немовля.",
            "Зроби комплімент кожному в кімнаті по черзі.",
            "Тримай планку, поки чекаєш на свій наступний хід.",
            "Засмійся найзлішим лиходійським сміхом.",
            "Зобрази свою улюблену тварину — звук і рухи.",
            "Придумай і проспівай 10-секундний джингл про цю компанію.",
            "Вдягни футболку задом наперед до наступного ходу.",
            "Зобрази драматичну смерть, як у кіно.",
            "Назви українську абетку у зворотному порядку від «М».",
            "Виголоси урочисту 20-секундну промову про свої шкарпетки.",
            "Потанцюй так, ніби ніхто не дивиться, 15 секунд.",
            "Зобрази ведучого новин, який читає прогноз погоди.",
            "Втримай ложку на носі 10 секунд.",
            "Розкажи анекдот. Якщо ніхто не засміявся — розкажи ще один.",
            "Говори пошепки до свого наступного ходу.",
            "Зроби 5 присідань, рахуючи вголос.",
            "Стань супергероєм: вигадай собі ім'я і суперсилу.",
            "Зобрази, як ти прокидаєшся в понеділок зранку.",
            "Поговори зі своєю рукою так, ніби це твій друг.",
            "Опиши смак води так, ніби ти сомельє.",
            "Покажи свій найкращий танцювальний рух.",
            "Говори про себе в третій особі до свого наступного ходу.",
            "Завмри статуєю, поки хтось не назве твоє ім'я.",
            "Проспівай, що ти робив(-ла) сьогодні, як в опері.",
            "Удавай, що підлога — лава, наступні 30 секунд.",
            "Покажи, як ти танцюєш на весіллі.",
            "Промов скоромовку три рази поспіль без помилок.",
            "Процитуй улюбленого кіногероя однією фразою.",
            "Зроби «вусики» з пальців і не прибирай до наступного ходу.",
            "Привітай кожного так, ніби не бачив(-ла) його 10 років.",
            "Проведи кулінарне шоу і «приготуй» уявну страву.",
        ],
    },
    "spicy": {
        "en": [
            "Let the group pick your profile photo for the next hour.",
            "Text the 3rd contact in your chats: 'I was just thinking about you'.",
            "Show the last thing you searched on your phone.",
            "Show the last meme you saved.",
            "Say your most-used emoji out loud.",
            "Show a screenshot of your home screen.",
            "Name your celebrity crush.",
            "Reveal a dream nobody here knows about.",
            "Show the last song you listened to.",
            "Confess the pettiest thing you did this month.",
            "Give a flirty wink to the person across from you.",
            "Name a nickname you'd never want to hear again.",
            "Show the oldest photo on your phone.",
            "Say how many alarms you set for tomorrow.",
            "Name your most-played song this year.",
            "Let the group ask you one question — answer it honestly.",
            "Play the last voice message you received.",
            "Tell us about a small hidden talent of yours.",
            "Show your screen time for today.",
            "Describe your ideal date in 15 seconds.",
            "Name the last thing that made you blush.",
            "Let the player on your right scroll your gallery back 5 photos.",
            "Name a show you secretly adore.",
            "Tell your worst date story.",
            "Show the last gif you sent.",
            "Admit who here you'd call first in a crisis, and why.",
            "Show what you saved your best friend's contact name as.",
            "Name a compliment you secretly want to hear.",
            "Play your favourite song and explain why it's yours.",
            "Tell us about your most awkward moment this week.",
            "Admit which childhood star you had a crush on.",
            "Name three things you're grateful for today.",
            "Show the last message you sent (cover the name).",
            "Re-enact your worst-ever flirting attempt.",
            "Confess your biggest crime against the fridge.",
            "Show the photo where you like yourself the most.",
            "Say how many browser tabs you have open right now.",
            "Name the song you secretly dance to alone.",
            "Give each person one sincere compliment, eye to eye.",
            "Reveal the wallpaper on your lock screen.",
        ],
        "uk": [
            "Дозволь компанії обрати тобі фото профілю на наступну годину.",
            "Напиши третьому контакту в чатах: «Я щойно про тебе згадав(-ла)».",
            "Покажи, що ти востаннє шукав(-ла) у телефоні.",
            "Покажи останній збережений мем.",
            "Назви вголос свій найчастіший емодзі.",
            "Покажи скриншот свого головного екрана.",
            "Назви свою знаменитість-краш.",
            "Розкрий мрію, про яку тут ніхто не знає.",
            "Покажи останню пісню, яку слухав(-ла).",
            "Зізнайся в найдріб'язковішому вчинку цього місяця.",
            "Кокетливо підморгни людині навпроти.",
            "Назви прізвисько, яке не хотів(-ла) би почути ще раз.",
            "Покажи найстаріше фото у своєму телефоні.",
            "Скажи, скільки будильників ти поставив(-ла) на завтра.",
            "Назви свою найпрослуханішу пісню цього року.",
            "Дозволь компанії поставити тобі одне запитання — відповідай чесно.",
            "Постав останнє голосове, яке тобі надіслали.",
            "Розкажи про свій маленький прихований талант.",
            "Покажи свій екранний час за сьогодні.",
            "Опиши своє ідеальне побачення за 15 секунд.",
            "Назви останнє, від чого ти зашарівся(-лася).",
            "Дозволь сусіду праворуч прогорнути твою галерею на 5 фото назад.",
            "Назви серіал, який таємно обожнюєш.",
            "Розкажи свою найгіршу історію з побачення.",
            "Покажи останній gif, який ти надсилав(-ла).",
            "Зізнайся, кому з присутніх подзвонив(-ла) би першим у халепі, і чому.",
            "Покажи, як підписаний контакт твого найкращого друга.",
            "Назви комплімент, який таємно хочеш почути.",
            "Постав свою улюблену пісню і поясни, чому вона твоя.",
            "Розкажи про найніяковішу ситуацію цього тижня.",
            "Зізнайся, у яку зірку дитинства був(-ла) закоханий(-а).",
            "Назви три речі, за які ти сьогодні вдячний(-а).",
            "Покажи останнє повідомлення, яке ти надіслав(-ла) (прикрий ім'я).",
            "Зобрази свою найгіршу спробу пофліртувати.",
            "Зізнайся у своїй найбільшій провині перед холодильником.",
            "Покажи фото, на якому ти собі найбільше подобаєшся.",
            "Скажи, скільки вкладок зараз відкрито у твоєму браузері.",
            "Назви пісню, під яку ти таємно танцюєш на самоті.",
            "Скажи кожному по щирому компліменту, дивлячись в очі.",
            "Покажи шпалери свого екрана блокування.",
        ],
    },
    "chaos": {
        "en": [
            "Swap one item of clothing with the player on your left.",
            "Sit in the seat of the player on your right; they take yours.",
            "Talk only in questions until your next turn.",
            "Ask the group for a new name and answer only to it for the rest of the game.",
            "Narrate everything you do out loud until your next turn.",
            "Do everything with your eyes closed until your next turn.",
            "Add a dramatic sound effect after each of your sentences.",
            "Pick an emoji and say it out loud before you speak, every time.",
            "Speak only in a whisper until two more spins happen.",
            "End every sentence with 'allegedly' until your next turn.",
            "Be the group's timer: announce each minute out loud.",
            "Wear something on your head until your next turn.",
            "Mirror the gestures of the person on your left for one minute.",
            "Talk about yourself in the third person until your next turn.",
            "Do everything with your non-dominant hand until your next turn.",
            "Invent a catchphrase and say it before every turn.",
            "Gasp dramatically whenever someone laughs, until your next turn.",
            "Repeat the last word of whoever speaks, for one minute.",
            "Stand up from your seat every time the turn passes to someone else.",
            "Give a solemn toast to a random object in the room.",
            "Dance for 5 seconds whenever it becomes your turn.",
            "Talk as if you're live-streaming this party.",
            "Pick a 'rival' here and agree with everything they say for one round.",
            "Talk at half speed until your next turn.",
            "Pretend to hold a microphone every time you speak.",
            "Swap seats with whoever spun the wheel before you.",
            "Make a 'ding' sound whenever someone picks up a phone.",
            "Don't show your teeth when you laugh, until your next turn.",
            "Tell everything like it's a deep secret, until your next turn.",
            "Sit upright like you're at a royal reception until your turn.",
            "Be the game's personal commentator for the next two minutes.",
            "Talk like you're freezing cold until your next turn.",
            "Say 'I officially declare' before each sentence.",
            "Pretend you're in slow motion for the next 30 seconds.",
            "Sing the players' names to the tune of any song.",
            "Hold your arms like a robot until your next turn.",
            "React to everything with an amazed 'wow!' until your next turn.",
            "Call '5 seconds of silence' — and stay silent the whole time yourself.",
            "Before each player spins, loudly predict what they'll land.",
            "Be an auctioneer 'selling' the nearest object to the room.",
        ],
        "uk": [
            "Поміняйся одним предметом одягу з гравцем ліворуч.",
            "Сядь на місце гравця праворуч, а він — на твоє.",
            "Говори лише запитаннями до свого наступного ходу.",
            "Попроси компанію дати тобі нове ім'я й відгукуйся лише на нього до кінця гри.",
            "Озвучуй уголос усе, що робиш, до свого наступного ходу.",
            "Роби все із заплющеними очима до свого наступного ходу.",
            "Після кожної своєї фрази додавай драматичний звуковий ефект.",
            "Обери собі емодзі й вимовляй його щоразу перед тим, як говорити.",
            "Говори лише пошепки, доки не відбудуться ще два спіни.",
            "Закінчуй кожне речення словом «нібито» до наступного ходу.",
            "Стань таймером компанії: оголошуй уголос кожну хвилину.",
            "Носи щось на голові до свого наступного ходу.",
            "Повторюй жести людини ліворуч протягом хвилини.",
            "Говори про себе в третій особі до свого наступного ходу.",
            "Роби все недомінантною рукою до свого наступного ходу.",
            "Вигадай собі фразу-візитівку й кажи її щоразу перед своїм ходом.",
            "Драматично ахай щоразу, коли хтось засміється, до наступного ходу.",
            "Повторюй останнє слово кожного, хто говорить, протягом хвилини.",
            "Вставай зі стільця щоразу, коли хід переходить до іншого.",
            "Виголоси урочистий тост випадковому предмету в кімнаті.",
            "Танцюй 5 секунд щоразу, коли настає твій хід.",
            "Говори так, ніби ведеш прямий ефір про цю вечірку.",
            "Обери собі «суперника» й погоджуйся з усім, що він каже, один раунд.",
            "Говори вдвічі повільніше до свого наступного ходу.",
            "Удавай, що тримаєш мікрофон, щоразу як говориш.",
            "Поміняйся місцями з тим, хто крутив колесо перед тобою.",
            "Видавай звук «дзинь» щоразу, коли хтось бере телефон.",
            "Не показуй зуби, коли смієшся, до свого наступного ходу.",
            "Розповідай усе так, ніби це велика таємниця, до наступного ходу.",
            "Сиди рівно, як на королівському прийомі, до свого ходу.",
            "Будь персональним коментатором гри наступні дві хвилини.",
            "Говори так, ніби тобі дуже холодно, до свого наступного ходу.",
            "Кажи «офіційно заявляю» перед кожним реченням.",
            "Удавай, що ти на сповільненому відео, наступні 30 секунд.",
            "Проспівуй імена гравців на мелодію будь-якої пісні.",
            "Тримай руки, як робот, до свого наступного ходу.",
            "Реагуй на все здивованим «ого!» до свого наступного ходу.",
            "Оголоси «5 секунд тиші» — і сам(-а) мовчи весь цей час.",
            "Перед спіном кожного гравця гучно передбачай, що йому випаде.",
            "Зобрази ведучого аукціону, який «продає» найближчий предмет.",
        ],
    },
}


def deck_cards(deck: str, lang: str) -> list[str]:
    """Cards for deck+lang. Falls back: unknown lang → 'en', unknown
    deck → 'mild'. Logs the fallback; never raises (no silent failure)."""
    resolved_deck = deck if deck in DECKS else "mild"
    if resolved_deck != deck:
        log.warning("punishment.unknown_deck", requested=deck)
    langs = DECKS[resolved_deck]
    if lang in langs:
        return langs[lang]
    log.warning("punishment.unknown_lang", requested=lang, deck=resolved_deck)
    return langs["en"]
