/**
 * Audio manifest — every sound the app ever plays is declared here.
 *
 * Spec §11 lists 10 sounds. The `.mp3` assets live in
 * `apps/webapp/public/sounds/`, generated by `scripts/generate_sounds.py`
 * (procedural synth, original / no third-party license — see
 * `docs/audio-licenses.md`). A missing file still fails silently, so the
 * app stays functional with no audio if one is ever absent.
 */

export const AUDIO_NAMES = [
  "ui_tap",
  "ui_swipe",
  "wheel_tick",
  "wheel_launch",
  "result_chime",
  "hoba_pop",
  "confetti_burst",
  "chaos_event",
  "join_ping",
  "rigged_reveal",
  "winner_fanfare",
] as const;

export type AudioName = (typeof AUDIO_NAMES)[number];

interface AudioDef {
  src: string;
  /** Relative volume in [0, 1]; multiplied by master volume at playback. */
  volume?: number;
}

export const AUDIO_MANIFEST: Record<AudioName, AudioDef> = {
  ui_tap: { src: "/sounds/ui_tap.mp3", volume: 0.55 },
  ui_swipe: { src: "/sounds/ui_swipe.mp3", volume: 0.5 },
  wheel_tick: { src: "/sounds/wheel_tick.mp3", volume: 0.55 },
  wheel_launch: { src: "/sounds/wheel_launch.mp3", volume: 0.8 },
  result_chime: { src: "/sounds/result_chime.mp3", volume: 0.8 },
  hoba_pop: { src: "/sounds/hoba_pop.mp3", volume: 1.0 },
  confetti_burst: { src: "/sounds/confetti_burst.mp3", volume: 0.7 },
  chaos_event: { src: "/sounds/chaos_event.mp3", volume: 0.7 },
  join_ping: { src: "/sounds/join_ping.mp3", volume: 0.5 },
  rigged_reveal: { src: "/sounds/rigged_reveal.mp3", volume: 0.85 },
  winner_fanfare: { src: "/sounds/winner_fanfare.mp3", volume: 0.95 },
};

/** Looping in-room background music — handled separately from one-shot SFX. */
export const MUSIC_SRC = "/sounds/bg_music.mp3";
export const MUSIC_VOLUME = 0.22;
